services:
  postgres:
    image: postgres:15
    container_name: order_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - order_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - order_network

  orderservice:
    build:
      context: ./order-service
      dockerfile: ./WebAPI/Dockerfile
    container_name: order_service
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_ENVIRONMENT: Development
    networks:
      - order_network

volumes:
  pgdata:

networks:
  order_network: